adm/urls.py
from django.conf.urls import url
from adm import views
from django.contrib.auth.decorators import login_required

app_name = 'adm'

urlpatterns = [
    url(r'^users/?$', login_required(views.users), name="users"),
    url(r'^user/(?P<pk>\d+)/?$', login_required(views.UserDeleteView.as_view()), name="user_delete"),
    url(r'^products/?$', login_required(views.ProductView.as_view()), name="admin_products"),
    url(r'^orders/?$', login_required(views.orders), name="admin_orders"),
    url(r'^order/(?P<pk>\d+)/?$', login_required(views.OrderDeleteView.as_view()), name="order_delete"),
    url(r'^import/?$', login_required(views.upload), name="import"),
    url(r'^product/(?P<pk>\d+)/?$', login_required(views.ProductDeleteView.as_view()), name="product_delete"),
]

front/urls.py
from django.conf.urls import url
from front import views

app_name = 'front'

urlpatterns = [
    url(r'^order/$', views.order, name="order"),
    url(r'^add/(?P<pk>\d+)/(?P<amount>\d+)/$', views.add_order, name="add_order"),
    url(r'login/$', views.signin, name='login'),
    url(r'logout/$', views.logout_view, name='logout'),
]

shaurman/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from front import views as front_view

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('adm/', include('adm.urls')),
    url('user/', include('front.urls')),
    url('', front_view.products, name="products"),
]

adm/models.py
from django.db import models
from django.contrib.auth.models import User
from djmoney.models.fields import MoneyField


class Product(models.Model):
    title = models.CharField(max_length=200)
    restaurant = models.CharField(max_length=200)
    price = MoneyField(max_digits=10, decimal_places=2, default_currency='UAH')

    def __str__(self):
        return self.title


class Order(models.Model):
    user = models.ForeignKey(User)
    product = models.ForeignKey(Product)
    date = models.DateTimeField()
    amount = models.IntegerField(default=1)

    def __str__(self):
        return "{} - {} for {} at {}".format(self.product, self.amount, self.user, self.date)

front/models.py
from django.db import models

# Create your models here.

adm/forms.py
from django.forms import ModelForm
from adm.models import Product


class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ['title', 'restaurant', 'price']

adm/views.py
from django.contrib.auth.models import User
from .models import Product, Order
from django.shortcuts import render, reverse
from django.core.urlresolvers import reverse_lazy
from django.core.files.storage import FileSystemStorage
import re
import os
from django.db import IntegrityError
from django.core.mail import EmailMessage
from shaurman import settings
from django.views.generic.edit import FormMixin
from django.views.generic import ListView
from adm.forms import ProductForm
from django.http import Http404
from django.views.generic import DeleteView
from django.utils.datastructures import MultiValueDictKeyError

EMAIL_REGEX = re.compile(r"[^@]+@[^@]+\.[^@]+")


def users(request):
    users = User.objects.all()
    return render(request, 'adm/users.html', {'users': users})


class FormListView(FormMixin, ListView):

    def get_success_url(self):
        return reverse('admin_products')

    def get(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        self.form = self.get_form(form_class)

        self.object_list = self.get_queryset()
        allow_empty = self.get_allow_empty()
        if not allow_empty and len(self.object_list) == 0:
            raise Http404((u"Empty list and '%(class_name)s.allow_empty' is False.")
                          % {'class_name': self.__class__.__name__})

        context = self.get_context_data(object_list=self.object_list, form=self.form)
        return self.render_to_response(context)

    def post(self, request, *args, **kwargs):
        return self.get(request, *args, **kwargs)

    def get_queryset(self):
        return Product.objects.all()


class ProductView(FormListView):
    model = Product
    form_class = ProductForm
    template_name = 'adm/products.html'

    def post(self, request, *args, **kwargs):
        form = ProductForm(request.POST)
        print(request.POST)
        if form.is_valid():
            form.save()
        return super().post(request, *args, **kwargs)


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('adm:admin_products')


class OrderDeleteView(DeleteView):
    model = Order
    success_url = reverse_lazy('adm:admin_orders')


class UserDeleteView(DeleteView):
    model = User
    success_url = reverse_lazy('adm:users')


class ListProduct(ListView):
    model = Product
    template_name = 'adm/products.html'


def orders(request):
    orders = Order.objects.all()
    return render(request, 'adm/orders.html', {'orders': orders})


def upload(request):
    try:
        if request.method == 'POST' and request.FILES['myfile']:
            myfile = request.FILES['myfile']
            fs = FileSystemStorage()
            filename = fs.save(myfile.name, myfile)
            file_str = [line.rstrip('\n') for line in fs.open(filename, 'r')]
            os.remove(os.path.join(settings.MEDIA_ROOT, str(filename)))
            status_dict = []
            for file_line in file_str:
                user_str = file_line.split(',')
                try:
                    if EMAIL_REGEX.match(user_str[2]):
                        try:
                            password = User.objects.make_random_password()
                            user = User.objects.create_user(user_str[2], user_str[2], password)
                            user.first_name = user_str[0]
                            user.last_name = user_str[1]
                            user.save()
                            email = EmailMessage('Registration at shaurman',
                                                 'Registration at shaurman is complete. Your Username is {} Your password is {}'.format(
                                                     user_str[2], password), to=[user_str[2]])
                            email.send()
                        except IntegrityError:
                            status_dict.append(user_str[2] + " user is exist")
                except IndexError:
                    status_dict.append(file_line + " bad line format")
            if len(status_dict) > 0:
                return render(request, 'adm/upload.html', {'errors': status_dict})
            return render(request, 'adm/upload.html', {
                'successes': "all users added successful"
            })
    except MultiValueDictKeyError:
        pass
    return render(request, 'adm/upload.html')

front/views.py
from django.shortcuts import render, redirect
from adm.models import Product, Order
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.contrib.auth import authenticate, login, logout


def products(request):
    products = Product.objects.all()
    return render(request, 'front/products.html', {'products': products})


@login_required
def order(request):
    orders = Order.objects.filter(user=request.user)
    return render(request, 'front/order.html', {'orders': orders})


@login_required
def add_order(request, pk, amount):
    if request.method == 'POST':
        order = Order(user=request.user, product=Product.objects.get(pk=pk), date=timezone.now(), amount=amount)
        order.save()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def signin(request):
    if request.method == 'POST':
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is not None:
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST['next'])
            return redirect('products')
        else:
            return render(request, 'front/login.html', {'error': 'Passwords or user didn\'t match'})
    else:
        return render(request, 'front/login.html')


def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('products')

templates/adm/orders.html
{% extends 'admin_base.html' %}
{% block content %}
<head>
    <meta charset="UTF-8">
    <title>Orders</title>
</head>
<body>
<h1>Orders</h1>
<hr>
<div class="container">
    <div class="row">
        <div class="col">User</div>
        <div class="col">Product</div>
        <div class="col">Amount</div>
        <div class="col">Date</div>
        <div class="col">Delete</div>
    </div>
    <hr>
{% for order in orders.all %}
    <div class="row">
        <div class="col">{{ order.user }}</div>
        <div class="col">{{ order.product }}</div>
        <div class="col">{{ order.amount }}</div>
        <div class="col">{{ order.date }}</div>
        <div class="col"><form action="{% url 'adm:order_delete' order.pk %}" method="POST">{% csrf_token %} <input class="btn btn-outline-danger" type="submit" value="x"/> </form></div>
    </div>
    <hr>
{% endfor %}
    </div>
</body>
{% endblock %}

templates/adm/products.html
{% extends 'admin_base.html' %}
{% block content %}
{% load djmoney %}
<head>
    <meta charset="UTF-8">
    <title>Products</title>
</head>
<body>
<h1>Products</h1>
<hr>
<div class="container">
    <div class="row">
        <div class="col">
            Title:
        </div>
        <div class="col">
            Restaurant:
        </div>
        <div class="col">
            Price:
        </div>
        <div class="col">
        </div>
    </div>
    <form action="" method="post">{% csrf_token %}
        <div class="row">
            <div class="col">
                {{ form.title }}
            </div>
            <div class="col">
                {{ form.restaurant }}
            </div>
            <div class="col">
                {{ form.price }}
            </div>
            <div class="col">
                <input type="submit" value="Send message"/>
            </div>
        </div>
    </form>
<hr>
    {% for product in object_list %}
    <div class="row">
        <div class="col">
            {{ product.title }}
        </div>
        <div class="col">
            {{ product.restaurant }}
        </div>
        <div class="col">
            {{ product.price }}
        </div>
        <div class="col">
            <form action="{% url 'adm:product_delete' product.pk %}" method="POST">{% csrf_token %}<input class="btn btn-outline-danger" type="submit"
                                                                                                          value="x"/>
            </form>
        </div>
    </div>
    <hr>
    {% endfor %}
</div>

</body>
{% endblock %}

templates/adm/upload.html
{% extends 'admin_base.html' %}
{% block content %}
<head>
    <meta charset="UTF-8">
    <title>Import Users</title>
</head>
<body>
<h1>Import Users</h1>
<hr>
{% load static %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input class="btn btn-primary" type="file" name="myfile">
    <button class="btn btn-primary" type="submit">Upload</button>
</form>
<hr>
{% if errors %}
<div class="container">
    {% for error in errors %}
    <div class="row">
        {{error}}
    </div>
    <hr>
    {% endfor %}
</div>
{% endif %}

{% if successes %}
<p>{{ successes }}</p>
<hr>
{% endif %}

<p><a href="{% url 'adm:users' %}">Return to home</a></p>
<hr>
</body>
{% endblock %}

templates/adm/users.html
{% extends 'admin_base.html' %}
{% block content %}
<head>
    <meta charset="UTF-8">
    <title>Users</title>
</head>
<body>
<h1>Users</h1>
<hr>
<div class="container">
    <div class="row">
        <div class="col">Username</div>
        <div class="col">First Name</div>
        <div class="col">Last Name</div>
        <div class="col">Email</div>
        <div class="col">
            Delete User
        </div>
    </div>
    <hr>
    {% for usr in users.all %}
    <div class="row">
        <div class="col">{{ usr.username }}</div>
        <div class="col">{{ usr.first_name }}</div>
        <div class="col">{{ usr.last_name }}</div>
        <div class="col">{{ usr.email }}</div>
        <div class="col">
            <form action="{% url 'adm:user_delete' usr.pk %}" method="POST">
                {% csrf_token %}
                <input class="btn btn-outline-danger" type="submit" value="x"/>
            </form>
        </div>
    </div>
    <hr>
    {% endfor %}
</div>
</body>
{% endblock %}

templates/admin_base.html
<!doctype html>
<html lang="en">
<head>
    <title>Admin Panel</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css"
          integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="container">
            <a class="navbar-brand" href="{% url 'adm:admin_products' %}">Admin Panel</a>
        <a class="navbar-brand" href="{% url 'products' %}">Products</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active"><a class="nav-link" href="{% url 'adm:import' %}">Import Users</a></li>
                <li class="nav-item active"><a class="nav-link" href="{% url 'adm:users' %}">Users</a></li>
                <li class="nav-item active"><a class="nav-link" href="{% url 'adm:admin_products' %}">Products</a></li>
                <li class="nav-item active"><a class="nav-link" href="{% url 'adm:admin_orders' %}">Orders</a></li>
                {% if user.is_authenticated %}
                <li class="nav-item active"><a class="nav-link" href="#" onclick="document.getElementById('logout_form').submit()">Logout</a></li>
                <form id="logout_form" method="post" action="{% url 'front:logout' %}">
                    {% csrf_token %}
                    <input type="hidden">
                </form>
                {% else %}
                <li class="nav-item active"><a class="nav-link" href="{% url 'front:login' %}">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<div class="container">
{% block content %}
{% endblock %}
</div>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"
        integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"
        integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ"
        crossorigin="anonymous"></script>
</body>
</html>

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <title>Shavuha</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css"
          integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="{% url 'products' %}">Products</a>
        <a class="navbar-brand" href="{% url 'adm:admin_products' %}">Admin Panel</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active"><a class="nav-link" href="{% url 'front:order' %}">Order</a></li>
                {% if user.is_authenticated %}
                <li class="nav-item active"><a class="nav-link" href="#"
                                               onclick="document.getElementById('logout_form').submit()">Logout</a></li>
                <form id="logout_form" method="post" action="{% url 'front:logout' %}">
                    {% csrf_token %}
                    <input type="hidden">
                </form>
                {% else %}
                <li class="nav-item active"><a class="nav-link" href="{% url 'front:login' %}">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<div class="container">
    {% block content %}
    {% endblock %}
</div>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"
        integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"
        integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ"
        crossorigin="anonymous"></script>
</body>
</html>

templates/front/login.html
{% extends 'base.html' %}
{% block content %}
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
<h1>Login</h1>
<form method="POST" action="{% url 'front:login' %}">
    {% csrf_token %}
    {% if request.GET.next %}
    <input type="hidden" name="next" value="{{ request.GET.next }}"/>
    {% endif %}
    Username:
    <br/>
    <input type="text" name="username"/>
    <br/>
    Password:
    <br>
    <input type="password" name="password"/>
    <br/>
    {% if error %}
    {{error}} <br>
    {% endif %}
     <br>
    <input class="btn btn-primary" type="submit" name="Login In!">
</form>
</body>
{% endblock %}

templates/front/order.html
{% extends 'base.html' %}
{% block content %}
<head>
    <meta charset="UTF-8">
    <title>Orders</title>
</head>
<body>
<h1>Orders</h1>
<hr>
<div class="container">
    <div class="row">
        <div class="col">Product</div>
        <div class="col">Amount</div>
        <div class="col">Date</div>
    </div>
    <hr>
{% for order in orders.all %}
    <div class="row">
        <div class="col">{{ order.product }}</div>
        <div class="col">{{ order.amount }}</div>
        <div class="col">{{ order.date }}</div>
    </div>
    <hr>
{% endfor %}
    </div>
{% endblock %}

templates/front/products.html
{% extends 'base.html' %}
{% block content %}
{% load djmoney %}
<head>
    <meta charset="UTF-8">
    <title>Products</title>
</head>
<body>
<h1>Products</h1>
<hr>
<div class="container">
<div class="row">
        <div class="col">
            Title:
        </div>
        <div class="col">
            Restaurant:
        </div>
        <div class="col">
            Price:
        </div>
        <div class="col">
        </div>
    </div>
    <hr>
{% for product in products.all %}
<div class="row">
        <div class="col">
            {{ product.title }}
        </div>
        <div class="col">
            {{ product.restaurant }}
        </div>
        <div class="col">
            {{ product.price }}
        </div>
        <div class="col">
            <form action="{% url 'front:add_order' product.pk 1 %}" method="POST">{% csrf_token %} <input class="btn btn-outline-success" type="submit" value="+"/> </form>
        </div>
    </div>
<hr>
{% endfor %}
    </div>
</body>
{% endblock %}